services:
  - type: web
    name: allroads-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
